version: "3"

services:
  nextjs:
    build: ./frontend
    container_name: nextjs
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  fastapi:
    build: ./backend
    container_name: fastapi
    expose:
      - "8000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
    - GEMINI_API_KEY=${GEMINI_API_KEY}

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs
      - fastapi
